import React from 'react';

const About = () => {
  return (
    <div>
        <p>ISTJ<br />Tranquilo, serio, gana el &eacute;xito por minuciosidad y confiabilidad. Pr&aacute;ctico, realista y responsable. Decida l&oacute;gicamente lo que se debe hacer y trabaja para lograrlo de manera constante, independientemente de las distracciones. Disfruta de hacer que todo est&eacute; ordenado y organizado: su trabajo, su hogar, su vida. Valorar las tradiciones y la lealtad.</p>
        <p>ISFJ<br />Tranquilo, amable, responsable y concienzudo. Comprometido y constante en el cumplimiento de sus obligaciones. Concienzudo, meticuloso y preciso. Leales, considerados, notan y recuerdan detalles sobre las personas que son importantes para ellos, preocupados por c&oacute;mo se sienten los dem&aacute;s. Esforzarse por crear un ambiente ordenado y armonioso en el trabajo y en el hogar.</p>
        <p>INFJ<br />Buscar significado y conexi&oacute;n en ideas, relaciones y posesiones materiales. Quiere entender lo que motiva a las personas y es perspicaz acerca de los dem&aacute;s. Conscientes y comprometidos con sus firmes valores. Desarrollar una visi&oacute;n clara sobre la mejor manera de servir al bien com&uacute;n. Organizados y resolutivos en la implementaci&oacute;n de su visi&oacute;n.</p>
        <p>INTJ<br />Tener mentes originales y gran empuje para implementar sus ideas y lograr sus objetivos. Ve r&aacute;pidamente patrones en eventos externos y desarrolla perspectivas explicativas de largo alcance. Cuando est&aacute; comprometido, organiza un trabajo y lo lleva a cabo. Esc&eacute;pticos e independientes, tienen altos est&aacute;ndares de competencia y desempe&ntilde;o, para ellos mismos y para los dem&aacute;s.</p>
        <p>ISTP<br />Tolerantes y flexibles, observadores silenciosos hasta que aparece un problema, luego act&uacute;an r&aacute;pidamente para encontrar soluciones viables. Analiza lo que hace que las cosas funcionen y obtiene f&aacute;cilmente grandes cantidades de datos para aislar el n&uacute;cleo de los problemas pr&aacute;cticos. Interesado en causa y efecto, organiza hechos utilizando principios l&oacute;gicos, valora la eficiencia.</p>
        <p>ISFP<br />Tranquilo, amable, sensible y amable. Disfruta del momento presente, de lo que sucede a su alrededor. Les gusta tener su propio espacio y trabajar dentro de su propio marco de tiempo. Leales y comprometidos con sus valores y con las personas que son importantes para ellos. No le gustan los desacuerdos y los conflictos, no impone sus opiniones o valores a los dem&aacute;s.</p>
        <p>INFP<br />Idealista, leal a sus valores ya las personas que son importantes para &eacute;l. Quieren una vida externa que sea congruente con sus valores. Curioso, r&aacute;pido para ver posibilidades, puede ser un catalizador para implementar ideas. Busca comprender a las personas y ayudarlas a alcanzar su potencial. Adaptable, flexible y tolerante a menos que un valor se vea amenazado.</p>
        <p>INTP<br />Buscan desarrollar explicaciones l&oacute;gicas para todo lo que les interesa. Te&oacute;rico y abstracto, interesado m&aacute;s en las ideas que en la interacci&oacute;n social. Tranquilo, contenido, flexible y adaptable. Tener una habilidad inusual para enfocarse en profundidad para resolver problemas en su &aacute;rea de inter&eacute;s. Esc&eacute;ptico, a veces cr&iacute;tico, siempre anal&iacute;tico.</p>
        <p>ESTP<br />Flexibles y tolerantes, adoptan un enfoque pragm&aacute;tico centrado en resultados inmediatos. Las teor&iacute;as y las explicaciones conceptuales los aburren, quieren actuar en&eacute;rgicamente para resolver el problema. Se concentra en el aqu&iacute; y ahora, espont&aacute;neo, disfruta cada momento que puede estar activo con los dem&aacute;s. Disfruta de las comodidades materiales y el estilo. Aprende mejor haciendo.</p>
        <p>ESFP<br />Extrovertida, amable y tolerante. Amantes exuberantes de la vida, las personas y las comodidades materiales. Disfruta trabajar con otros para hacer que las cosas sucedan. Aporta sentido com&uacute;n y un enfoque realista a su trabajo, y hace que el trabajo sea divertido. Flexible y espont&aacute;neo, se adapta f&aacute;cilmente a nuevas personas y entornos. Aprende mejor probando una nueva habilidad con otras personas.</p>
        <p>ENFP<br />C&aacute;lidamente entusiasta e imaginativo. Ve la vida como llena de posibilidades. Hace conexiones entre eventos e informaci&oacute;n muy r&aacute;pidamente y procede con confianza en funci&oacute;n de los patrones que ve. Quiere mucha afirmaci&oacute;n de los dem&aacute;s, y est&aacute; dispuesto a dar aprecio y apoyo. Espont&aacute;neos y flexibles, suelen confiar en su capacidad de improvisaci&oacute;n y en su fluidez verbal.</p>
        <p>ENTP<br />R&aacute;pido, ingenioso, estimulante, alerta y franco. Ingenioso para resolver problemas nuevos y desafiantes. Experto en generar posibilidades conceptuales y luego analizarlas estrat&eacute;gicamente. Bueno para leer a otras personas. Aburrido por la rutina, rara vez har&aacute; lo mismo de la misma manera, propenso a volverse hacia un nuevo inter&eacute;s tras otro.</p>
        <p>ESTJ<br />Pr&aacute;ctico, realista, pr&aacute;ctico. Decisivo, moverse r&aacute;pidamente para implementar decisiones. Organiza proyectos y personas para hacer las cosas, se enfoca en obtener resultados de la manera m&aacute;s eficiente posible. Cuida los detalles de la rutina. Tener un conjunto claro de est&aacute;ndares l&oacute;gicos, seguirlos sistem&aacute;ticamente y querer que otros tambi&eacute;n lo hagan. Contundente en la ejecuci&oacute;n de sus planes.</p>
        <p>ESFJ<br />Cari&ntilde;oso, concienzudo y cooperativo. Quieren armon&iacute;a en su entorno, trabajan con determinaci&oacute;n para establecerla. Me gusta trabajar con otros para completar las tareas con precisi&oacute;n y a tiempo. Leal, sigue hasta en los asuntos peque&ntilde;os. Se fija en lo que los dem&aacute;s necesitan en su d&iacute;a a d&iacute;a y trata de proporcion&aacute;rselo. Quieren ser apreciados por lo que son y por lo que aportan.</p>
        <p>ENFJ<br />C&aacute;lido, emp&aacute;tico, receptivo y responsable. Muy en sinton&iacute;a con las emociones, necesidades y motivaciones de los dem&aacute;s. Encuentra potencial en todos, quiera ayudar a otros a alcanzar su potencial. Pueden actuar como catalizadores para el crecimiento individual y grupal. Leal, sensible a los elogios y las cr&iacute;ticas. Sociable, facilita a otros en un grupo y proporciona un liderazgo inspirador.</p>
        <p>ENTJ<br />Franco, resolutivo, asume el liderazgo con facilidad. Ve r&aacute;pidamente procedimientos y pol&iacute;ticas il&oacute;gicos e ineficientes, desarrolla e implementa sistemas integrales para resolver problemas organizacionales. Disfruta de la planificaci&oacute;n a largo plazo y el establecimiento de metas. Suelen estar bien informados, leer bien, disfrutar ampliando sus conocimientos y transmiti&eacute;ndolos a otros. Contundente en la exposici&oacute;n de sus ideas.</p>
    </div>
  );
};

export default About;